service: electivaparcial
frameworkVersion: '3'

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: python3.9

functions:
  api:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
